Disallow running scripts as root

diff --git a/build b/build
--- a/build
+++ b/build
@@ -143,6 +143,15 @@ function parse_options()
 
 parse_options "$@"
 
+if [[ `/usr/bin/id -u` -lt 1024 ]]; then
+	echo "ERROR: you can only run this script with a user whose UID is at least 1024. Current user: `/usr/bin/id`"
+	exit 1
+fi
+if [[ `/usr/bin/id -g` -lt 1024 ]]; then
+	echo "ERROR: you can only run this script with a user whose GID is at least 1024. Current user: `/usr/bin/id`"
+	exit 1
+fi
+
 if tty -s; then
 	TTY_ARGS="-t -i"
 else
