Integrate with Jenkins

diff --git a/create_project b/create_project
--- a/create_project
+++ b/create_project
@@ -3,8 +3,8 @@ PROJECT_DIR="$1"
 GIT_URL="$2"
 
 if [[ "$PROJECT_DIR" = "" || "$GIT_URL" = "" ]]; then
-	echo "Usage: ./create_project <DIR> <GIT_URL>"
-	exit 1
+  echo "Usage: ./create_project <DIR> <GIT_URL>"
+  exit 1
 fi
 
 set -e
@@ -12,8 +12,13 @@ set -e
 project_dir_parent=`dirname "$PROJECT_DIR"`
 fstype=`df -T "$project_dir_parent" | tail -n 1 | awk '{ print $2 }'`
 if [[ "$fstype" == vmhgfs || "$fstype" == vboxfs ]]; then
-	echo "You cannot put the project dir in a VMWare or VirtualBox shared folder."
-	exit 1
+  echo "You cannot put the project dir in a VMWare or VirtualBox shared folder."
+  exit 1
+fi
+
+if [[ `id -u` != 0 ]]; then
+  echo "You must run this command with root privileges."
+  exit 1
 fi
 
 set -x
@@ -30,4 +35,7 @@ mkdir "$PROJECT_DIR/build"
 echo "$GIT_URL" > "$PROJECT_DIR/git_url"
 (cd "$PROJECT_DIR" && ln -s build/log/state.log state.log)
 
+chown -R jenkins: "$PROJECT_DIR"
 chmod u=rwx,g=x,o= "$PROJECT_DIR" "$PROJECT_DIR/cache"
+setfacl -m u:www-data:x "$PROJECT_DIR" "$PROJECT_DIR/repo"
+setfacl -d -m u:www-data:x "$PROJECT_DIR/repo"
