Work in progress

diff --git a/create_project b/create_project
--- a/create_project
+++ b/create_project
@@ -11,6 +11,17 @@ set -e
 
 CONTAINER_APP_UID=9999
 
+project_dir_parent=`dirname "$PROJECT_DIR"`
+fstype=`df -T "$project_dir_parent" | tail -n 1 | awk '{ print $2 }'`
+if [[ "$fstype" == vmhgfs || "$fstype" == vboxfs ]]; then
+	echo "You cannot put the project dir in a VMWare or VirtualBox shared folder."
+	exit 1
+fi
+if [[ `whoami` != root ]]; then
+	echo "You must run this program as root."
+	exit 1
+fi
+
 set -x
 
 mkdir -p "$PROJECT_DIR"
