Overhaul Jenkins release script.
Use parameters instead of environment variables.

diff --git a/jenkins_release b/jenkins_release
--- a/jenkins_release
+++ b/jenkins_release
@@ -1,6 +1,14 @@
 #!/bin/bash
 set -e
 
+SELFROOT=`dirname "$0"`
+SELFROOT=`cd "$SELFROOT" && pwd`
+
+PROJECT_DIR=
+PASSENGER_DIR=
+CONCURRENCY=1
+EXTRA_ARGS=
+
 function run()
 {
   echo "$ $@"
@@ -16,31 +24,75 @@ function cleanup()
   fi
 }
 
-if [[ "$PASSENGER_ROOT" = "" ]]; then
-  echo "Please set PASSENGER_ROOT."
-  exit 1
-fi
-if [[ "$PROJECT_NAME" = "" ]]; then
-  echo "Please set PROJECT_NAME."
-  exit 1
-fi
+function usage()
+{
+  echo "Usage: ./jenkins_release [OPTIONS]"
+  echo "Build RPMs and YUM repository. To be invoked from Jenkins."
+  echo
+  echo "Required options:"
+  echo "  -p PATH         Path to a project"
+  echo
+  echo "Optional options:"
+  echo "  -P PATH         Path to Phusion Passenger source directory"
+  echo "  -j CONCURRENCY  Build concurrency (default: $CONCURRENCY)"
+  echo "  -O ARG          Extra arguments to pass to build script"
+}
+
+function parse_options()
+{
+  local OPTIND=1
+  local opt
+  while getopts "p:P:j:O:h" opt; do
+    case "$opt" in
+    p)
+      PROJECT_DIR="$OPTARG/git"
+      ;;
+    P)
+      PASSENGER_DIR="$OPTARG"
+      ;;
+    j)
+      CONCURRENCY="$OPTARG"
+      ;;
+    O)
+      EXTRA_ARGS="$OPTARG"
+      ;;
+    h)
+      usage
+      exit
+      ;;
+    *)
+      return 1
+      ;;
+    esac
+  done
+
+  if [[ "$PROJECT_DIR" = "" ]]; then
+    echo "Please specify a project using -p."
+    exit 1
+  fi
+}
+
+parse_options "$@"
+
 if [[ `whoami` != jenkins ]]; then
   echo "This script may only be run from Jenkins."
   exit 1
 fi
 
-SELFROOT=`dirname "$0"`
-SELFROOT=`cd "$SELFROOT" && pwd`
-CONCURRENCY=${CONCURRENCY:-1}
-
 echo "$ cd $SELFROOT"
 cd "$SELFROOT"
 
-run ./build \
-  -p "/srv/passenger_rpm_automation/$PROJECT_NAME" \
-  -P "$PASSENGER_ROOT" \
-  -j "$CONCURRENCY" \
+BUILD_ARGS=(
+  -p "/srv/passenger_rpm_automation/$PROJECT_NAME"
+  -j "$CONCURRENCY"
   -l
+  $EXTRA_ARGS
+)
+if [[ "$PASSENGER_DIR" != "" ]]; then
+  BUILD_ARGS+=(-P "$PASSENGER_DIR")
+fi
+
+run ./build "${BUILD_ARGS[@]}"
 run ./repo_update \
   -p "/srv/passenger_rpm_automation/$PROJECT_NAME" \
   -s auto-software-signing@phusion.nl \
